excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://JWilson90.github.io
title: The Hungry Archaeologist
tagline: Cultural Preservation and Revival Through the Stomachs of the World
description: My awesome new site
paginate: 5