excerpt_separator: ""
pygments: rouge
markdown: kramdown
highlighter: rouge
url: http://JWilson90.github.io
title: JWilson90
tagline: A log of everyday life
description: My awesome new site
paginate: 5
